name: compiler CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install antlr4
        run: |
          cd /usr/local/lib
          sudo curl -O https://www.antlr.org/download/antlr-4.9-complete.jar

      - name: mvn
        run: |
            mvn clean install
            mvn exec:java
